server:
  port: 8888
  servlet:
    context-path: /boot

#    mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml #  扫描映射文件

  type-aliases-package: com.qf.sprningboot.entity #  设置别名扫描的包

  configuration:
    map-underscore-to-camel-case: true #    开启驼峰映射设置


spring:
  datasource: #    连接数据库信息
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///db_air?serverTimezone=UTC
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  elasticsearch:
    jest:
      proxy:
        host: 192.168.206.128
        port: 9200
logging:
  level:
    com.qf.sprningboot.mapper: DEBUG
